### ISSUE TITLE
视频播放有BUG

### ISSUE THREAD

**Issue by StormPhoenix** [LuoboDcom/ZZShow#3]
视频播放功能有BUG。点击播放按钮，程序就会崩溃。

机型：
Genymotion 模拟器
Name：Custom Phone-6.0.0-API 23 - 768×1280 
AOSP Version：6.0
Genymotion version：2.8.0

错误日志如下：
12-22 23:04:19.815 1874-1874/com.ys.yoosir.zzshow E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.ys.yoosir.zzshow, PID: 1874
                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.ys.yoosir.zzshow-2/lib/x86/libijkffmpeg.so: has text relocations
                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                        at java.lang.System.loadLibrary(System.java:1076)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:215)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:211)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:202)
                                                                        at com.ys.yoosir.zzshow.utils.mediavideo.IjkVideoView.createPlayer(IjkVideoView.java:999)
                                                                        at com.ys.yoosir.zzshow.utils.mediavideo.IjkVideoView.openVideo(IjkVideoView.java:298)
                                                                        at com.ys.yoosir.zzshow.utils.mediavideo.IjkVideoView.access$2200(IjkVideoView.java:59)
                                                                        at com.ys.yoosir.zzshow.utils.mediavideo.IjkVideoView$7.onSurfaceCreated(IjkVideoView.java:651)
                                                                        at com.ys.yoosir.zzshow.utils.mediavideo.TextureRenderView$SurfaceCallback.onSurfaceTextureAvailable(TextureRenderView.java:265)

... .... ....

12-22 23:04:19.860 1874-1882/com.ys.yoosir.zzshow E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:893)
                                                                at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by LuoboDcom** [comment]
这个是 ijkplayer 出现了Bug，更新一下 ijkplayer的版本试下

**Comment by LuoboDcom** [comment]
这个是 ijkplayer 出现了Bug，更新一下 ijkplayer的版本，应该会解决掉
